<head>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<?php
include_once 'header.php';

include 'db_conn.php';

// Check if the ID is provided in the URL
if (isset($_GET['id'])) {
    $patientID = $_GET['id'];

    // Retrieve patient information from the database using the provided ID
    $sql = "SELECT * FROM patients WHERE id = ?;";
    $stmt = mysqli_stmt_init($conn);

    if (!mysqli_stmt_prepare($stmt, $sql)) {
        // Handle the error appropriately (e.g., show an error message)
        die("Statement preparation failed.");
    }

    mysqli_stmt_bind_param($stmt, "i", $patientID);
    mysqli_stmt_execute($stmt);

    $result = mysqli_stmt_get_result($stmt);

    // Check if a patient is found with the provided ID
    if ($row = mysqli_fetch_assoc($result)) {
        // Display patient information here
        echo "Patient ID: " . $row['id'] . "<br>";
    } else {
        // Handle the case when no patient is found with the provided ID
        echo "Patient not found.";
    }

    mysqli_stmt_close($stmt);
} else {
    // Handle the case when no ID is provided in the URL
    echo "Invalid patient ID.";
}
?>

         <!-- Card Content  -->
<div class="firstSec">
    <div class="head">
      <?php echo '<h2 class="mb-4"> Patient Name: '.$row['lname'] .', '.$row['fname'] .' '.$row['mname'] .'</h2> '?>
    <a href="prenatal.php"><button type="button" class="right-button btn"><i class='bx bx-arrow-back'></i>Back</button></a>
    </div>
</div>



   <!-- INSERT HERE!!!  -->

   

<div class="thirdSec" id="thirdSec">
<div class="card">
    <div class="card-header">
        <div class="d-flex justify-content-between">
            <ul class="nav nav-tabs card-header-tabs button-container-left">
                <li class="nav-item">
                    <a class="nav-link active button" aria-current="true" role="button" data-tab="first_trimester">First Trimester</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link button" aria-current="false" role="button" data-tab="second_trimester">Second Trimester</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link button" aria-current="false" role="button" data-tab="third_trimester">Third Trimester</a>
                </li>
            </ul>
            <ul class="nav nav-tabs card-header-tabs second-nav-tabs button-container-right">
                <li class="nav-item">
                    <a class="nav-link active button" aria-current="true" role="button" data-tab="first_checkup">First Check-up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link button" aria-current="false" role="button" data-tab="second_checkup">Second Check-up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link button" aria-current="false" role="button" data-tab="third_checkup">Third Check-up</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="card-body">
        <div class="tab-content">
            <div class="tab-pane active" id="contenttab">
                 <h5 class="card-title">Content Tab</h5>
                 <div id="formContainer">
            <!-- The form generated by JavaScript will be inserted here -->
                </div>
            </div>
        </div>
    </div>
</div>

    </div>



    <?php
include_once 'footer.php'
?>